### ISSUE TITLE
`EncodeHQ-CBR` sometimes crashes when slices are not all same size

### ISSUE THREAD

**Issue by mossblaser** [bbc/vc2-reference#11]
Given a slice size which doesn't exactly divide the transform coefficients the
encoder will sometimes crash.

For example with the following [sample frame (1 frame, 10 bit, 1280x720, 4:2:2, progressive, YCbCr)](https://github.com/bbc/vc2-reference/files/4823981/linear_ramps.zip):

    $ EncodeHQ-CBR \
        -x 1280 -y 720 -f 4:2:2 -l 10 -r 6 \
        -k LeGall -d 3 -a 1 -u 1 -s $((1280*720*2*2/4)) \
        pictures.16p2 out2.vc2
    EncodeHQ-CBR: ../../src/boost/multi_array/view.hpp:317: boost::detail::multi_array::multi_array_view<T, NumDims>& boost::detail::multi_array::multi_array_view<T, NumDims>::operator=(const ConstMultiArray&) [with ConstMultiArray = boost::multi_array<int, 2>; T = int; long unsigned int NumDims = 2]: Assertion `std::equal(other.shape(),other.shape()+this->num_dimensions(), this->shape())' failed.
    Aborted (core dumped)

I have also seen in the past (but have failed to reproduce for this report)
cases where encoding succeeds but produces an invalid output. Specifically, the
encoder will sometimes set the VC-2 level value to something which explicitly
prohibits non-constant slice sizes. In other cases, I've also seen corrupted
outputs produced.

**Comment by GalenReich** [comment]
### Explanation of Error
In the given example the error occurs during the CBR mode's calculation of the quantisation indices by the `quantIndicesCBR` function.

During the calculation, the wavelet transform coefficients are split into slices using the `split_into_blocks` function. 

Each slice is then passed to the `quantise_transform_np` function which carries out three processes:
  1. Splits the block into subbands using the `split_into_subbands` function
  2. Quantises the block
  3. Merges the subbands using the `merge_subbands` function

The error is thrown in the 3rd step, and occurs because the `split_into_blocks` function produces blocks of size 8x8 (from 2^waveletDepth = 8) for the luma component and blocks of size 4x8 for the chroma components (because of the 4:2:2 subsampling). `split_into_subbands` and `merge_subbands` assume (without checking) that the height and width of the block are both multiples of 2^waveletDepth. In this case the width is not.

Increasing the horizontical slice size (-a / --hSlice) from 1 to 2 fixes the problem because the subsampling is 4:2:2 and the block sizes become 16x16 (luma) and 16*8 (chroma).

### Open Questions

  1. What behaviour is seen for 4:2:0 subsampling?
  2. What's the best way to fix this?
  3. Is there still a bug that occurs when "slices are not all same size"? How to reproduce?

**Comment by GalenReich** [comment]
4:2:0 Subsampling has a similar effect in the vertical (as well as horizontal) dimensions. The vertical slice size (-u / --vSlice) must be increased from 1 to 2 for encoding to succeed.

More generally, hSlice must be even for 4:2:2, and vSlice and hSlice must be even for 4:2:0

**Comment by GalenReich** [comment]
### Wider Issue

This problem also crops up in the quantise_block(const ConstView2D& block, const Array2D& qIndices) function, which is used by **all encoding modes**. This fault occurs silently in this function and results in two calculations being made for the same output block.

In this example code block, when the evenness constraint on hSlice and vSlice are not satisfied, `yBlocks` and `xBlocks` can be greater than `blockHeight` and `blockWidth` respectively resulting in an integer division to 0. Because of this, multiple assignments are made to the same `sliceIndices` of `quantisedBlock` - these assignments use different `qIndices` as `y` and `x` change as expected. 

```
for (int y=0, top=0, bottom=blockHeight/yBlocks; y<yBlocks; ++y, top=bottom, bottom=((y+1)*blockHeight/yBlocks) ) {
    for (int x=0, left=0, right=blockWidth/xBlocks; x<xBlocks; ++x, left=right, right=((x+1)*blockWidth/xBlocks) ) {
           // Define the samples within the current slice/codeblock
           const ArrayIndices2D sliceIndices = indices[Range(top,bottom)][Range(left,right)];
           quantisedBlock[sliceIndices] = quantise_block(block[sliceIndices], qIndices[y][x]);
    }
}
```

**Comment by GalenReich** [comment]
### Solution 

Solution is to enforce that slice sizes exactly divide the padded picture dimensions.

This is different to the standard which allows for varying slice subband sizes in 13.5.6.2 (Slice Subband Area).

**Comment by jamesba** [comment]
Since v3, the standard has recommended not doing that, though, hasn't it? And the levels standard requires you not to do that if your level is non-zero.
